### ISSUE TITLE
Colours sequences need to be escaped when rendering messages

### ISSUE THREAD

**Issue by jugglerchris** [lumail/lumail2#121]
If an e-mail contains a sequence such as `$[RED]`, it ends up being interpreted when rendering, garbling the output.

**Comment by skx** [comment]
If you can handle this then that would be appreciated - I still have nightmares about the display-code.

If not I'll have a look once I've finished working on the IMAP support sometime next week.

**Comment by skx** [comment]
I'm going to break this down into two steps:

* We should be able to escape the colour formatting.
      * `$[RED|UNDERLINE]This is red` will show, in red, underlined, "`This is red`"
      * `$$[RED]This is normal` will show the literal string `$$[RED]This is normal`.
* The Lua side will replace `$[RED...` with `$$[RED` for message-bodies.

**Comment by skx** [comment]
The C++ side is bogus, and doesn't cope with leading coloured-strings.

I'll work on it.

The Lua side is done for the moment, albeit simplistically.

**Comment by skx** [comment]
OK I had a rethink and some experimentation this evening.  Updating the regular expression to capture both `$[BLUE]...` and `$$[BLUE]...` didn't work out well, because things weren't greedy enough.

Instead I have a new plan:

* If there is text of the form `$[BLUE]Text $[RED]Red` then it will be handled as per currently.
* If there is text of the form `$[BLUE]Text $[#RED]still blue` then the second one will be escaped.

This means the lua code must transform message-bodies such that `$[COLOUR|CODE]Text` becomes `$[#COLOUR|CODE]Text`, and the C++ side must transform `$[#BLUE]` into `$[BLUE]`, leaving the colour the same.

This will handle both required parts, and will be much simpler, since I only have to special-case the expansion of the colour - where I can easily select `colour.at(0) == '#'`.

Expect this to be handled soon.

**Comment by jugglerchris** [comment]
What happens if the original message contains $[#RED] ?

**Comment by skx** [comment]
Then it will be displayed as `$[RED]`.

**Comment by jugglerchris** [comment]
That would make the e-mails from this issue kind of hard to read.  :-)
I haven't had time to follow this recently, but I don't see why this is better than just $->$$ escaping, which at least is simple enough to avoid these edge cases.  (The C++ needs to handle all instances of $ rather than just searching for $[...])
Would you consider an alternate way of specifying colours which is actually out of band?  eg instead of "Test $[BLUE|UNDERLINE]blue", pass something like `{ "Test ", {"blue", attr="BLUE|UNDERLINE"}}`?  (I'd be motivated to implement this at some point, though I'm a bit busy in the near future).

**Comment by skx** [comment]
I'd be happy to accept a patch which allowed this to show "red - blue" only:

$[RED]red $$[green]green $[BLUE]

But I couldn't make the code work.  The specific issue is this regexp in the parser:

      pcrecpp::RE re("^(.*)\\$\\[([#a-zA-Z|]+)\\](.*)$");

Changing  that to this doesn't work (because the .* is greedy):

      pcrecpp::RE re("^(.*)\\$+\\[([#a-zA-Z|]+)\\](.*)$");

I think this solution is neat, and correct.  I'm open to the previous idea but I think that the parsing is harder than you'd expect - and I'd prefer to keep it simple.

**Comment by skx** [comment]
PS.  There's standalone code here which I used for experimenting:

* https://github.com/lumail/experiments/tree/master/colour-string
