### ISSUE TITLE
Fetch message headers only

### ISSUE THREAD

**Issue by gber** [lumail/lumail2#140]
Looking at `/etc/lumail2/perl.d/get-messages` it appears that when opening an IMAP mailbox every single message is downloaded.
I have several GB of email and mailboxes for mailing lists which contain thousands of messages, I access them via IMAP (currently using mutt) rather than using something like fetchmail or offlineimap because I only read them selectively and don't want to waste bandwidth and disk space on my computers. Also, opening such mailboxes with lumail takes several minutes currently.
Moreover, in case of GMail tags are mapped to IMAP mailboxes, so downloading every single message means that the same message would be downloaded multiple times if it has multiple tags.

Would it be possible to only fetch and cache the headers and fetch the body only on demand (and possibly without attachments) like other MUAs?

**Comment by skx** [comment]
> Looking at /etc/lumail2/perl.d/get-messages it appears that when opening an IMAP mailbox every single message is downloaded.

Yes.  This was the initial pass at adding IMAP support so that is the case.

>  Moreover, in case of GMail tags are mapped to IMAP mailboxes, so downloading every single message means that the same message would be downloaded multiple times if it has multiple tags.

This is also true.  (Largely because I've tested against GMail, but I mostly use it upon my own IMAP server where this isn't a problem.)

In an ideal case I'd cache based on :
 
     $prefix/$uuid/N

Rather than:

      $prefix/$folder/$id

I'll need to rework things in the near future to avoid re-downloading all the messages.  For some mailboxes, which I've been testing upon, in the region of 1-500 messages it works well.

**Comment by gber** [comment]
Would you consider downloading headers only and messages only on demand though?
I really like lumail's concept of a small core and scriptability, and I've been annoyed by mutt for many years and would love to get rid of it, but reasonable performance is a killer feature. The largest mailbox I have has currently 119473 messages, it takes ca. 6 seconds to open in mutt (with the tokyocabinet DB cache enabled).

**Comment by skx** [comment]
> Would you consider downloading headers only and messages only on demand though?

Yes.

To recap this is what currently happens when you open a folder:

* We call `get-messages` to open a link to the IMAP server, and it returns the body, flags, and ID of every message.
* For every message downloaded:
     * We write it to local-disk, if it isn't present already.
     * We create a new CMessage object with that local path.

The big problem here is that we download the message even if it is already present, and we do so in one hugely blocking loop.  (Because this evolved from only read-dir against "`~/Maildir/foo/{cur new tmp}`".)

There is *no* getting away from the fact we need the mail locally, but we can do better.

I think the solution would be two-fold:

* Create each message when opening the folder, but do so emptily.
* Allow CMessage to get its own body/header on-demand.

That would mean opening a folder would involve:

* Selecting the folder, to get the list of IDs.
* For each ID create an empty CMessage object with the remote ID.
     * When CMessage::get_body() is called download the body on-demand.
     * When CMessage:headers() is called download the body on-demand.

We'd still have the issue that we have to download every _header_ to display the list of messages (i.e. We display From:, Subject: , Flags, etc.) but that should be quicker than the bodies too.

**Comment by skx** [comment]
The specific problem with the current implementation is that the CMessage object has no way to get its own body - it just relies on that having been downloaded already.

However there is a solution:

* Write a simple perl script that listens on a Unix domain socket, and which keeps a connection open to the IMAP-server.
* Change from opening folders/messages via calls to perl to use this persistent socket instead.
      *  e.g. "folder_list\n";
      * e.g. "message_list\n";
      * e.g. "change_flags\n";

That will avoid the overhead of opening fresh connections each time, keep our concerns separate, and allow the IMAP-state to be shared between CGlobal and CMessage neatly.

As an aside it will also improve the debugging situation in #139 / #141

**Comment by skx** [comment]
I have a proof of concept update which changes things such that we run a persistent daemon to talk to IMAP, which can be talked to over  a unix domain-socket.  This replaces all the individual scripts in `perl.d`.

With this deamon running we can cheaply make calls to the remote IMAP server to:

* list folders
* list message-ids
* get messages
* delete messages
* etc.

This means we can now update the code in `CMessage` to load the body in a lazy-fashion, on-demand, if it isn't already present.

If/When this code is deployed we'll be in a better place:

* We'll still need to download every message to show the index-view.
* But each message will be downloaded individually if it isn't present.  If it is present (i.e. has been downloaded previously) then that cached value will be used.

That means that opening a large folder will still be horrifically slow, but only the first time.  (As the locally cached messages will persist)

It might be that we need to make other changes, but we'll see how fast things are on the __second__ open once I've committed this work.  Expect it Saturday/Sunday.

(Using the persistent daemon is good; but the key change is the lazy-loading of message-bodies, and that's only possible because we can _easily_ fetch the body on demand, rather than having to shell out to perl.)

**Comment by gber** [comment]
Thanks for the quick reply, sounds good! A daemon with a persistent connection using the IDLE extension would also make it possible to signal lumail when new mail arrives without blocking the UI.
How about taking lazy loading a step further and only fetch the list of uids, the headers of the last 500 messages and create just dummy messages for the rest which are only fetched and filled in once they come into view? AFAIK that is the approach [Trojita](http://trojita.flaska.net/) uses and it is really fast and responsive.
Would it be possible to store the cached messages in a DB rather than the filesystem? In my case it would probably amount to literally a million small files which is probably not very performant (this became a problem on my server which is why I had to switch from Maildir to Dovecot's dbox format).

**Comment by skx** [comment]
> Thanks for the quick reply, sounds good!

Great.

>  A daemon with a persistent connection using the IDLE extension would also make it possible to 
> signal lumail when new mail arrives without blocking the UI.

I think that seems like something we could manage.


> How about taking lazy loading a step further and only fetch the list of uids, the headers of the last 500 messages and create just dummy messages for the rest which are only fetched and filled in once they come into view?

That would be the next step.  Even if I make lazy-loading the current setup of lumail is that we run operations like this to display the contents of a folder:

* Fetch the list of all messages.
* Call `Message:format()` on each one to get the entry to display on the screen.
* Show the appropriate messages.

So even if we lazy-load the message headers/bodies we do actually need them all to be present to format them for display.

Instead we should only format the messages which are actually visible on the screen.  That would be a huge win if we only have to call `Message:format()` 20 times, rather than 2000.   Once I've got the lazy-loading part done this will be the next change.

>Would it be possible to store the cached messages in a DB rather than the filesystem? 

I'd probably try to rule that out.  The IMAP code is obviously written based on the Maildir code, and recycling as much as possible.  That's why the IMAP implementation pretty much does "fetch to local folder", because there are so many assumptions that a mesasge is local.

Adding in a DB-layer, and using it instead of the local filesystem would complicate a lot of the implementation, and while it might allow new/interesting things I think the overhead would be something that I'd struggle to justify.

> In my case it would probably amount to literally a million small files which is probably not very performant (this became a problem on my server which is why I had to switch from Maildir to Dovecot's dbox format).

Yes this is a concern, I think I could be open to saving a DBM-hash of headers, instead of one file per message in the future.  But we'll have to wait and see.

**Comment by skx** [comment]
I've updated the internal implementation to simplify things.

To test - open two terminals.

Terminal One:
      export imap_username=steve
      export imap_password=secret
      export imap_server=imaps://imap.gmail.com
      ./perl.d/imapd

Terminal Two:
       ./lumail2 --load-file ./lumail2.lua

If you don't start the IMAP-proxy you see no mails.

Now I've cleaned up and moved the code into a simple wrapper which is globally available I can attack the real problems:

* Load message-bodies on-demand.
* Update the Lua layer to not format things that aren't visible on-screen.

**Comment by gber** [comment]
Following your instructions the IMAP proxy dies with the following error after lumail connects:

    $ perl /etc/lumail2/perl.d/imapd
    Accepted connection.
            Command: list_folders
    Use of uninitialized value $_[0] in substitution (s///) at /usr/share/perl5/Net/IMAP/Client.pm line 923, <GEN2> line 1.
    Use of uninitialized value $_[0] in substitution (s///) at /usr/share/perl5/Net/IMAP/Client.pm line 924, <GEN2> line 1.
    Use of uninitialized value $_[0] in concatenation (.) or string at /usr/share/perl5/Net/IMAP/Client.pm line 925, <GEN2> line 1.
    Accepted connection.
            Command: list_folders
    Use of uninitialized value $_[0] in substitution (s///) at /usr/share/perl5/Net/IMAP/Client.pm line 923, <GEN3> line 1.
    Use of uninitialized value $_[0] in substitution (s///) at /usr/share/perl5/Net/IMAP/Client.pm line 924, <GEN3> line 1.
    Use of uninitialized value $_[0] in concatenation (.) or string at /usr/share/perl5/Net/IMAP/Client.pm line 925, <GEN3> line 1.
    Accepted connection.
            Command: list_folders
    Use of uninitialized value $_[0] in substitution (s///) at /usr/share/perl5/Net/IMAP/Client.pm line 923, <GEN4> line 1.
    Use of uninitialized value $_[0] in substitution (s///) at /usr/share/perl5/Net/IMAP/Client.pm line 924, <GEN4> line 1.
    Use of uninitialized value $_[0] in concatenation (.) or string at /usr/share/perl5/Net/IMAP/Client.pm line 925, <GEN4> line 1.
    Accepted connection.
            Command: list_folders
    Use of uninitialized value $_[0] in substitution (s///) at /usr/share/perl5/Net/IMAP/Client.pm line 923, <GEN5> line 1.
    Use of uninitialized value $_[0] in substitution (s///) at /usr/share/perl5/Net/IMAP/Client.pm line 924, <GEN5> line 1.
    Use of uninitialized value $_[0] in concatenation (.) or string at /usr/share/perl5/Net/IMAP/Client.pm line 925, <GEN5> line 1.
    Accepted connection.
            Command: list_folders
    Use of uninitialized value $_[0] in substitution (s///) at /usr/share/perl5/Net/IMAP/Client.pm line 923, <GEN6> line 1.
    Use of uninitialized value $_[0] in substitution (s///) at /usr/share/perl5/Net/IMAP/Client.pm line 924, <GEN6> line 1.
    Use of uninitialized value $_[0] in concatenation (.) or string at /usr/share/perl5/Net/IMAP/Client.pm line 925, <GEN6> line 1.
    Can't use an undefined value as an ARRAY reference at /usr/share/perl5/Net/IMAP/Client.pm line 127, <GEN6> line 1.

**Comment by skx** [comment]
Those uninitialized variable warnings are coming from the fact that the reading of the username/password/imap-server from the environment are failing.

I think that means you've not run the export commands *before* starting the imapd process.

**Comment by skx** [comment]
Yeah on my Debian Jessie system `Client.pm` line 923 corresponds to `_string_quote` which is called around `$user` and `$pass`, in the function `login`.

Also other systems.

If you have `socat` installed you can test the list-folder operation like so:

       socat - UNIX-CONNECT:$HOME/.imap.sock

Then type `list_folders` and press return.

**Comment by gber** [comment]
Sorry, the problem was indeed in front of the computer, I used `imap_user` instead of `imap_username`, imapd works now.

However, lumail2 segfaults when trying to open a mailbox after imapd seems to have fetched the messages, [here is the backtrace](https://github.com/lumail/lumail2/files/101776/gdb.txt).

**Comment by skx** [comment]
OK so it fetches the message, and tries to draw them via the Lua function  `maildir_view()`, at some point in the middle of that it dies.

My immediate respond would be "`rm ~/.lumail2.cache`" to see if that helps.  If not we'll need further debugging.  Coding is hard.

**Comment by gber** [comment]
I've removed `~/.lumail2.cache` and `~/lumail2/cache/` and the crash is still happening.

**Comment by skx** [comment]
OK thanks.  It's obviously something to do with the `CMaildir` handling, but I can't spot anything obvious in the backtrace, and frustratingly the code seems to work as-is for me.

I'd planned to do the lazy-loading code next, but I guess i need to track this down first.

**Comment by skx** [comment]
I wonder if this patch would fix the problem:

      @@ -181,7 +181,7 @@ void CGlobalState::update_maildirs()
            */
           if (m_maildirs != NULL)
           {
      -        delete(m_maildirs);
      +//        delete(m_maildirs);
               m_maildirs = NULL;
           }

The crash seems to be relating to freeing the array of `CMaildir` objects.  This change would avoid that - at a cost of a memory leak.  If it does fix the problem then I can look further into it.

**Comment by gber** [comment]
This results in an imapd exception that looks similar to the one in issue #141 :

    Can't use string ("68") as an ARRAY ref while "strict refs" in use at /usr/share/perl5/Net/IMAP/Client.pm line 431, <GEN3> line 1.

**Comment by gber** [comment]
lumail2 doesn't crash any more and just prints an error that it couldn't parse imapd's truncated response:

    An error was caught Failed to parse JSON response to 'get_messages'.

**Comment by skx** [comment]
> lumail2 doesn't crash any more and just prints an error that it couldn't parse imapd's truncated response:

That's good news.  Yay, error-handling!

> Can't use string ("68") as an ARRAY ref while "strict refs" in use at /usr/share/perl5/Net/IMAP/Client.pm line 431, <GEN3> line 1.

I wonder why we're seeing this error.  It looks like we're fetching something via a scalar-ref, not an array-ref, or similar.  The code in question in `Client.pm` looks like it is inside `sub fetch()`.

I'd be curious where this is being called - in `get_message_ids` or similar?  Could you share the output of `perl.d/imapd` that comes up immediately prior to this error?

--

In happier news we've now got lazy-loading of message bodies.    In practice this doesn't change anything, but we're makign good progress:

* The folder list is shown.
* You select a folder.
      * We fetch the flags and IDs of every message.
      * We add an "empty" message to our list.
* Only when a message is operated upon do we fetch the body.

This should mean we only fetch the minimum we need.  In practice this doesn't quite work out as teh Lua layer tries to write a pretty index, which means reading the Subject, etc, of every message.  But now that this lazy-loading is present we can stop that such that we only format the *visible* messages - and that will mean that we only fetch what is absolutely required.

**Comment by gber** [comment]
> > lumail2 doesn't crash any more and just prints an error that it couldn't parse imapd's truncated response:
> 
> That's good news.  Yay, error-handling!

Of course, that's after commenting out the free() as you suggested, so there is still a bug somewhere.
When I put the delete back it prints the following when crashing:

    Terminate called after throwing an instance of 'char const*'

Could it be that you're freeing a const string?

> 
> > Can't use string ("68") as an ARRAY ref while "strict refs" in use at /usr/share/perl5/Net/IMAP/Client.pm line 431, <GEN3> line 1.
> 
> I wonder why we're seeing this error.  It looks like we're fetching something via a scalar-ref, not an array-ref, or similar.  The code in question in `Client.pm` looks like it is inside `sub fetch()`.

Perl's execptions are really unhelpful, here is the context:

    $ sed -n '415,431p' /usr/share/perl5/Net/IMAP/Client.pm

    sub fetch {
        my ($self, $msg, $keys) = @_;
        my $wants_many = undef;
        if (ref $msg eq 'ARRAY') {
            $msg = join(',', @$msg);
            $wants_many = 1;
        }
        if (ref $keys eq 'ARRAY') {
            $keys = join(' ', @$keys);
        }
        my ($ok, $lp) = $self->_tell_imap(FETCH => qq[$msg ($keys)], 1);
        if ($ok) {
            my @ret;
            foreach (@$lp) {
                my $tokens = _parse_tokens($_)->[3];
                push @ret, { @$tokens };



> 
> I'd be curious where this is being called - in `get_message_ids` or similar?  Could you share the output of `perl.d/imapd` that comes up immediately prior to this error?

Unfortunately that's all, before that are just imapd's diagnostic messages:

    Accepted connection.
            Command: list_folders
    Accepted connection.
            Command: get_messages INBOX
    Can't use string ("96") as an ARRAY ref while "strict refs" in use at /usr/share/perl5/Net/IMAP/Client.pm line 431, <GEN3> line 1.

> In happier news we've now got lazy-loading of message bodies.    In practice this doesn't change anything, but we're makign good progress:
> 
> * The folder list is shown.
> * You select a folder.
>       * We fetch the flags and IDs of every message.
>       * We add an "empty" message to our list.
> * Only when a message is operated upon do we fetch the body.
> 
> This should mean we only fetch the minimum we need.  In practice this doesn't quite work out as teh Lua layer tries to write a pretty index, which means reading the Subject, etc, of every message.  But now that this lazy-loading is present we can stop that such that we only format the *visible* messages - and that will mean that we only fetch what is absolutely required.

That sound very interesting!

**Comment by skx** [comment]
OK so to recap the current situation is:

* You need to comment out the call to `free()` - with that in place you get a crash which  I cannot see.
* Once that free is removed you're getting an error in the fetching of messages.

I've added diagnostics, and pushed.  You should now get a little more useful debugging information if you restart `perl.d/imapd`.

That said I've now actually fixed the bug which you opened:

* When a folder is opened we just look for a list of message-ids.
* Those are used to create faux/empty CMessage objects.
* When an empty CMessage object is operated upon it fetches its own body, if it wasn't already cached on-disk.
* The Lua layer has been updated to only foramt messages for display which are __visible__ on the screen.  This means that the whole thing actually works - we only fetch ~50 messages instead of 4000 when opening a large folder.

However to see this you'll need to add this to your config:

      Config:set( "index.sort", "none" )

Otherwise every message is fetched, such that the create-time can be used, and the messages sorted in-order.  Obviously our intention is to avoid that mass-fetch, so the cost is that sorting will be somewhat random.

Finally - I appreciate your patience and assistance in this discussion.  Obviously you're not making changes  yourself, but reporting these issues makes everything better for me, and other users.  Without the prompting and chasing I'd be inclined to live with slow access - because it's fast enough for me as-is, for example.

**Comment by gber** [comment]
> OK so to recap the current situation is:
> 
> * You need to comment out the call to `free()` - with that in place you get a crash which  I cannot see.
> * Once that free is removed you're getting an error in the fetching of messages.

Yes, that was the situation.

> 
> I've added diagnostics, and pushed.  You should now get a little more useful debugging information if you restart `perl.d/imapd`.
> 

Now with the new one by one fetching, imapd does not crash any more and I can now open the mailbox with lumail2.  I've tried multiple times scrolling through all messages of my INBOX, despite the free being commented out as you suggested in [your comment](#issuecomment-174163076) lumail2 randomly crashes, [here is a new backtrace](https://github.com/lumail/lumail2/files/101836/gdb.txt) 

> That said I've now actually fixed the bug which you opened:
> 
> * When a folder is opened we just look for a list of message-ids.
> * Those are used to create faux/empty CMessage objects.
> * When an empty CMessage object is operated upon it fetches its own body, if it wasn't already cached on-disk.
> * The Lua layer has been updated to only foramt messages for display which are __visible__ on the screen.  This means that the whole thing actually works - we only fetch ~50 messages instead of 4000 when opening a large folder.

Yes, that is already a huge improvement, thank you very much for working on this!

> However to see this you'll need to add this to your config:
> 
>       Config:set( "index.sort", "none" )
> 
> Otherwise every message is fetched, such that the create-time can be used, and the messages sorted in-order.  Obviously our intention is to avoid that mass-fetch, so the cost is that sorting will be somewhat random.

Right, but actually you can just ask the IMAP server to return the requested messages, e.g. the last 50, in sorted order (by date or thread), no need to fetch them all or sort them client-side.

Also instead of fetching the whole message for displaying the index, I don't know about how you handle messages internally but maybe you could just fetch the INTERNALDATE, from and subject header fields and use it to populate dummy messages? Then the whole message would only need to be fetched when the user actually wants to read the message and this would not need to be cached and eat up disk space either.

If you have some time, there are some good tips from the Dovecot developers at http://www.imapwiki.org/ClientImplementation

> Finally - I appreciate your patience and assistance in this discussion.  Obviously you're not making changes  yourself, but reporting these issues makes everything better for me, and other users.  Without the prompting and chasing I'd be inclined to live with slow access - because it's fast enough for me as-is, for example.

Sure thing, I would just love to be able to replace mutt.  Unfortunately I'm really bad with perl and have no clue about C++, so I really do appreaciate your efforts. Having GB's of mail and thousands of messages in an INBOX are nothing uncommon in the age of GMail so I'm sure performant IMAP support will make lumail2 useful to a lot of people.

**Comment by skx** [comment]
> Now with the new one by one fetching, imapd does not crash any more and I can now open the mailbox with lumail2. I've tried multiple times scrolling through all messages of my INBOX, despite the free being commented out as you suggested in your comment lumail2 randomly crashes, here is a new backtrace

Thanks.  I think I've worked out what is going on, and have pushed a fix.

> Yes, that is already a huge improvement, thank you very much for working on this!

No problem.

> Right, but actually you can just ask the IMAP server to return the requested messages, e.g. the last 50, in sorted order (by date or thread), no need to fetch them all or sort them client-side.

That is correct; but is not something I've yet added.  Only because the sorting happens externally at the moment - which was obviously required when we only operated upon Maildirs.

I suspect this heritage is going to cause issues in the future.

For the moment I've added the ability for a message to fetch its own (complete) body, on-demand.  This is less good than fetching _only_ the headers, and then the body when appropriate.  But there is an assumption I've made that we can always parse the message to count attachments, etc.


> Also instead of fetching the whole message for displaying the index, I don't know about how you handle messages internally but maybe you could just fetch the INTERNALDATE, from and subject header fields and use it to populate dummy messages? 

Sadly not.  Sure we have defaults such that the display of a list of messages shows:

* Flags
* Subject.
* Sender
* has_attachment, or not.

But the user can change those defaults, and users do.

Either I read all available headers for real, or the message is unformatted.  There's no real compromise here.   And because we need to parse the message __body__ to see if there are attachments, i.e. count the MIME-parts, that's why I'm fetching the body right now, not just the headers which seems to make logical sense.)

>If you have some time, there are some good tips from the Dovecot developers at http://www.imapwiki.org/ClientImplementation

Thanks.  I've been re-reading the IMAP spec today.  There are probably clever things that can be done in the future to improve things.  But obviously the priority is making it no-longer crash for you.

If the recent update kills the crash - replacing the free we removed - then I think we're good to close this and attack other issues in the future.

**Comment by gber** [comment]
Unfortunately, the random crashes are still there, here is the new [backtrace](https://github.com/lumail/lumail2/files/101871/gdb.txt)

**Comment by skx** [comment]
Thanks.

It is definitely a crash when freeing a CMaildir object, which is coming somewhere during/after the call to  `function maildir_vew()` in `lumail2.lua`.  There are only a few places where CMaildir objects are created/destroyed and all of them look good to me.

I'll run under valgrind and see if I can spot an error.

**Comment by skx** [comment]
I've misread that backtrace.  it is coming from `CMessage::headers()`.  Suggests parsing the message-failed.

I've added better diagnostics which should confirm that explicitly now.

**Comment by skx** [comment]
(I suspect you're trying to read an empty message - either the local cache is broken, or the imap-proxy is returning an empty body.  Will add a fallback case for that now.)

**Comment by gber** [comment]
lumail2 now shows the following error message:

    An error was caught Failed to open the message:/home/gber/.lumail2/cache//imaps:__<redacted>_/INBOX/3454
    An error was caught /etc/lumail2/lumail2.lua:168: attempt to index local 'hand' (a nil value)

This happens on random messages, I also delete the cache after each test run.

**Comment by skx** [comment]
The second error comes because you've not got a (Lua) cache file.  That's harmless.

The first error means we're making progress!  When we open a folder we get a list of message-ids.  For each one we create an empty CMessage object, storing the folder-name, and the ID.  

The intent is that when the message is accessed for real the body is fetched from the IMAP-server.  In your case, for some reason, this is failing somewhere.  The intent is that the call-chain would go:

* CMessage::header("Subject")
      * CMessage::headers()
      * CMessage::parse_message()
      * CMessage::lazy_load() 

I've added a call to strerr to see if we can find out *why* this open is failing.  But we're getting close!

**Comment by gber** [comment]
Ha, looks like it is running out of fds:

    An error was caught Failed to open the message file - not found: /home/gber/.lumail2/cache//imaps:__<redacted>_/INBOX/3456 Too many open files

**Comment by skx** [comment]
Gonna head away for a few hours; looks like I need to add some `close()` calls.  That's a simple fix though :)

**Comment by skx** [comment]
Hope the last update should resolve this problem; please close if it does.  If not I'll poke further.

**Comment by gber** [comment]
Yes, that fixed it. Thanks again.
