### ISSUE TITLE
Cannot figure out how to add maildirs to the configuration

### ISSUE THREAD

**Issue by hsanson** [lumail/lumail2#144]
Unless I am missing something I believe there is no documentation explaining how to add Maildirs to the configuration.

I read the API.md, README.md and samples and tried adding several things to the user configuration (.lumail2/lumail2.lua) without success. The client tells me I am in maildir mode but there are no maildirs.

My last attempt was to add the following to the top of the configuration:

    Config:set("maildir.prefix", "~/.mail")

where the .mail folder contains all my Maildirs, also tried full path and setting only one maildir path and it didn't work either.

**Comment by skx** [comment]
The default configuration-file `/etc/lumail2/lumail2.lua` contains a default set near the end - which I suspect is overwriting your addition at the top.

Ideally you'd run "make install", which would create `/etc/lumail2/lumail2.lua`.  That file would be read as the sane defaults and you'd add your personal configuration to the file `~/.lumail2/lumail2.lua` __or__ the file `~/.lumail2/$HOSTNAME.lua`.

In your case either of those would work, because both would load _after_ the default.  The defaults are set in this area of the code:

      --
      -- The default Maildir location is ~/Maildir
      --
      local def_maildir = HOME .. "/Maildir"
      
      --
      -- Set the maildir-prefix, if it exists.
      --
      -- NOTE: You could also set an array of prefixes.
      --
      -- To set multiple values simply configure a table, not a string:
      --
      -- Config:set( "maildir.prefix", { def_maildir, "/tmp/Maildir" } )
      --
      Config:set( "maildir.prefix", def_maildir );
      
I hope that helps?

**Comment by skx** [comment]
To recap use this if you need more than one path:

    Config:set( "maildir.prefix", { "/home/user/path1", "/home/user/path2" } )

And just this if you need one:

    Config:set( "maildir.prefix", "/home/user/.mail" )

**Comment by hsanson** [comment]
Worked!! 

Just a comment: those lines are too far at the bottom (line 2991 in the default config) making it difficult to find them.
Maybe better have a small sample configuration with the basics that can be used to bootstrap the local configuration
in HOME/lumail2/lumail2.lua.
