### ISSUE TITLE
index.sort = "date" is broken

### ISSUE THREAD

**Issue by fischerling** [lumail/lumail2#151]
Messages are not sorted by date.

The bug is in Message:to_ctime() at lumail.lua:509.

```lua
local success,output = pcall( date, str )

--                                   ^
--                                   |
--                                 str is not defined
```

**Comment by skx** [comment]
I'm surprised by this one, as I use sorting by dates successfully myself - unless I'm accidentally sorting by ctime of the files instead.

Regardless thank you for your bug report and pull-request, at first glance it seems reasonable but I'd want to test locally to confirm it is a suitable fix.

**Comment by skx** [comment]
Testing has confirmed that the bug is present, and your fix .. fixes it.

Thanks for your contribution!

If you have any general comments, or suggestions, I'd be happy to hear them by email.  Having somebody new to the project discover and fix two issues in one day is a rare thing, and I'd appreciate any comments you might have!
