### ISSUE TITLE
Required Feature: Curses

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#2]
The old code was a mess with a lot of GUI stuff scattered around.  At least the drawing code of getting/setting a view-offset was duplicated three times.

We should make sure that each view-mode has it's own View-class.

I expect five modes:

* view maildirs
* view messages
* view message
* view attachments/mime-parts
* view text-file

**Comment by jugglerchris** [comment]
I've found the lumail1 message mode a bit too restrictive. Features I'd like:
* Lua control of colours (eg quoted text in different colour, or boundaries between parts)
* More Lua control of layout; eg scroll headers/attachments instead of keeping fixed (I find it easier to tell if I've arrived at a new message), and I've had messages with so many attachments that lumail crashes with no space for body. :-) Also control of wrapping headers.

My purposed would be served by a way to let Lua convert a message object into a bunch of lines to display, including colour markup, and suppressing the header/attachment space.

UI stuff I've done and not fed back yet:
* Extend the colour markup to work within lines and in more places (including msg()).
* Implemented text wrapping in the body callback
* Added a callback to format an entry in the message list mode. With the message sorting, I've used that to implement threading.

A bit of a grab bag of comments - thought I should brain dump while you're working on it!

**Comment by skx** [comment]
Sorry for closing this mid-discussion.  I was adding this bug for the initial stub rather than a complete solution.  But yes I agree.

I expect that the message should be generated by Lua, and that the message should be a structure something like an array of lines+colour-pairs.

That was one of the reasons why I was quite pleased with the `show_message` function here:

* https://github.com/skx/lumail2/blob/master/show_message.lua

If we can write a default `Cessage:to_string()`, that users can override, then this simplifies the display.  We also allow users to do complex GPG-validation, and HTML-conversion, if they want.

I'd expect to add a new mode here too:

* `message` -> Show the message.
* `message_parts` -> Show the messageparts/attachments in a list for also-opening.  Though in that case they'd *NOT* be reformatted by lua.

I'm going to work some more on getting something that will draw different modes, and has a lua input-promptt, and then I can start looking at this seriously.

One thing is for sure I don't want to have all the code-duplication we had in the past.

**Comment by jugglerchris** [comment]
That all sounds good!
