### ISSUE TITLE
lumail don't closes files

### ISSUE THREAD

**Issue by fischerling** [lumail/lumail2#220]
Lately lumail behaved weird (can't display maildirs or even exit) because it
hit the limit of open files.

* System(s): Arch Linux
* Gmime:  2.6.20
* lumail2: master

I tested it on two machines: one with my configuration and one with a clean install.
On both the problem occurred.

## Problem

*Note*: The cache may hides this, especially with ```index.fast``` set to 1.

The files opened by CMessage::parse_message() don't get closed.

I tried two solutions:

```diff
diff --git a/src/message.cc b/src/message.cc
index 4d7377e..a565ab3 100644
--- a/src/message.cc
+++ b/src/message.cc
@@ -187,6 +187,7 @@ GMimeMessage * CMessage::parse_message()
    }
      
    stream = g_mime_stream_fs_new(fd);
+   g_mime_stream_fs_set_owner ((GMimeStreamFs *) stream, true);
    parser = g_mime_parser_new_with_stream(stream);
    g_object_unref(stream);
```
and

```diff
diff --git a/src/message.cc b/src/message.cc
index 4d7377e..cb5ce9f 100644
--- a/src/message.cc
    +++ b/src/message.cc
@@ -236,6 +236,7 @@ GMimeMessage * CMessage::parse_message()
        CFile::delete_file(file);

    g_object_unref(parser);
+   close(fd);
    return (message);
}
```
However the second worked, I don't really know why this is happening and if just
closing the file is a good solution.

**Comment by skx** [comment]
Thanks for diagnosing and reporting on a possible fix.  I'm not at my best today so I'm not going to look into it immediately, but Wed/Thurs I should be more alive.

I will note that I've seen this in the old implementation where it was reported/fixed in [this bug](https://github.com/lumail/lumail/issues/124) so it seems like a regression.

I'll go over the CMessage object carefully soon to make sure we're closing it, but it does seem like a potential problem and adding a `close` _should_ be harmless..

**Comment by skx** [comment]
Just for reference I found that if I added a `close` as per your second solution the end result was that no body was returned, via `get_parts()`.

Hence the stalling / delay here.
