### ISSUE TITLE
assertion 'G_IS_OBJECT (object)' failed

### ISSUE THREAD

**Issue by RquasiR** [lumail/lumail2#292]
With d737d I get sometimes the above error message during sorting (by date). We had that already with commit 7c7589817ccde3d325c29d8ce739faf8e9a178da. The error message might be data depending
because it doesn't happen during invoking all subfolders of ~/maildir. And there aren't as much errors as messages in the subfolder. Strange that I sometimes can re-invoke an "error-giving" subfolder without any error-messages (as above) or with a message (in my language) meaning "memory access error".

Rudolf

![lumail2-d737d-error-message](https://cloud.githubusercontent.com/assets/15799290/25516611/d80525e8-2beb-11e7-90b3-a52f8ef9a5de.png)

**Comment by skx** [comment]
I think there are two possible causes here:

* A particular message has a bogus header/mime-setup such that parsing it with gmime fails.
* I'm doing something wrong in my code.

I guess what is happening for you is that parsing a particular message, set of messages, is failing, which is resulting in a bogus value being cached.  So something like this:

* If the `date` header is not already cached
   * Parse the message to fetch it.
   * Write that to the cache.

This is probably enough to explain why it doesn't happen every time.  To track this down I'll need to see a message that is failing, which will be a process of elimination:

* If you copy all messages into a temporary maildir.
* Then delete your cache `~/.lumail2/cache/d737d` in your screenshot above.

At that point it should show the warning __every__ time you relaunch the client.  It'll then be a process of elimination to delete messages until you only have a couple that are failing.  If we can then pin it down to a message, or group of messages, I can try to work out what is going wrong if you're willing to share them with me.

**Comment by RquasiR** [comment]
OK.
I prepared a group of 5 messages which shows the error thrice.
I'll send it to you.
Sorry for make you work on Labour Day ... :-)

Rudolf

**Comment by skx** [comment]
I've received your mail, and I can confirm I see the same problem you reported.  Here's hoping it is an easy fix!

As for Labour Day - I'm in Finland and I have no idea what that is!  I wouldn't worry though, if I'm busy I ignore bug reports until I'm not :)

**Comment by skx** [comment]
So to recap the following error is visible when opening the folder with the "bad" messages:

      (process:24000): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

So that points to a call to `g_object_unref` being to blame.  I edited `src/message.cc` and commented out every single call to `g_object_unref` - this would mean we'd not free/unreference some of the objects.   Once that was done I confirmed:

* We were leaking memory.
* The warning/error/message was gone.

I re-enabled the calls one by one to see which was to blame.  Eventually I found this was failing:

       std::vector<std::shared_ptr<CMessagePart> >CMessage::get_parts()
       {
           GMimeMessage *message = parse_message();
           m_parts.push_back(part2obj(mime_part));
           g_object_unref(message);
       }

That code (which is simplified) looks fine:

* Parse the message.
* Do something with it.
* Free it.

But if you look in `part2obj` there is __one__ case where the message is retrieved and free'd:

    else if (GMIME_IS_MESSAGE_PART(part))
    {

        /*
         * Populate `mem` with the data.
         */
        GMimeMessage *msg = g_mime_message_part_get_message(GMIME_MESSAGE_PART(part));
        g_mime_object_write_to_stream(GMIME_OBJECT(msg), mem);
        g_object_unref(msg);
    }

So I think the conclusion is that this code is wrong:

* We get the parent message.
* We do something with it
* We free it.

That leads to a double-free, which causes an error.
