### ISSUE TITLE
Error in 1922 when saving message elsewhere

### ISSUE THREAD

**Issue by RquasiR** [lumail/lumail2#293]
The error is to be seen in the appended picture of the panel.

When a message is saved to another folder it should be sorted there and deleted in the original folder.
I fear this is not as simple as it is written here.

Much work for "Labour Day" (= 1st  May, I think in Finland too) ... :-)

Rudolf

![lumail2-1922-error-when saving-messages-elswhere](https://cloud.githubusercontent.com/assets/15799290/25554556/4ff9b976-2cd0-11e7-8082-ae581c625eb2.png)

**Comment by skx** [comment]
So you're viewing a message, you press `s` to save, you then enter a destination and receive that error?

Could you show me what is on line 1888 of your `lumail2.lua` file?  

And verify you're using a current git clone - I recently changed the way saving works as a result of a similar bug [which you can see here](https://github.com/lumail/lumail2/issues/288) so I'd want to make sure you were up to date.?

**Comment by RquasiR** [comment]
Yes, so I do: "s" to save the message elsewhere; lumail2 asks for destination and then
I receive the error on line 1888.

In lumail2.lua line 1888 is the line directly after the function line:

function Message.save (dest)

  -- The message we're going to work on.
  local msg = Message.at_point()


I fetched all programs this morning to get the newest ones, so I think to use the current git clone. 
ls cache in .lumail2 says "1922".

Rudolf

**Comment by RquasiR** [comment]
I remember what you wrote to #288.
I think, if I'm using the newest git clone I haven't to correct the code. Am I wrong?

Rudolf

**Comment by skx** [comment]
> I think, if I'm using the newest git clone I haven't to correct the code. Am I wrong?

That's right.

I can't reproduce this here, and it seems like you're dying [on the very first line](https://github.com/lumail/lumail2/blob/master/lumail2.lua#L1888) of the function, which is odd.  Because prompting for the destination happens __after__ that.

I'd suggest two things:

* Can you redirect stderr to see if anything is logged?  Something like:
    *  `make ; ./lumail2  --load-file ./lumail2.lua  --load-path ./lib  2> error.log`
    * Then view `error.log` to look for output.
* Let me know if you're building against Lua 5.1, 5.2, or 5.3?  

There __must__ be more happening here than it seems, since if the function is dying you'd never be prompted for a destination at all.  You could sanity-check `~/.lumail2/*.lua` to make sure there is no old code relating to saves, from previous issue too.

**Comment by skx** [comment]
**Edit**: Add `--no-default` first:

      $ make ; ./lumail2 --no-default --load-file ./lumail2.lua --load-path ./lib 2> error.log

**Comment by RquasiR** [comment]
$ make ; ./lumail2 --no-default --load-file ./lumail2.lua --load-path ./lib 2> error.log

gives me no longer any error! How could that happen? 
What should I do next? Using lumail2 as normal and try again "s" in order to try to reproduce the error?

make sayd Nothing to be done for 'default'. Where do I see which version of Lua is used?

**Comment by RquasiR** [comment]
Invoking lumail2, going into a subfolder and trying to "s" a mail brings the error again (line 1888).

**Comment by skx** [comment]
> gives me no longer any error! How could that happen?

I _think_ that means that your global file, located at `/etc/lumail2/lumail2.lua`, is outdated.    You've presumably installed in the past, and not updated that recently.  (Either that or `~/.lumail2/lumail2.lua`. )

> make sayd Nothing to be done for 'default'.

Great, that means your built binary is up to date.

> Where do I see which version of Lua is used?

The `Makefile` will tell you, or you can press `L` in lumail, and look at the top-line.  I see:

      This is Lumail2 version b5b7-dirty <Lua 5.3>

**Comment by skx** [comment]
> Invoking lumail2, going into a subfolder and trying to "s" a mail brings the error again (line 1888).

So not fixed then.  Anything in the stderr logfile?

**Comment by RquasiR** [comment]
"L" in lumail: This is Lumail2 version 1922 <Lua 5.2>
Nothing in error.log in folder lumail2/

**Comment by skx** [comment]
So I'm confused right now: First of all you said it was fixed, when invoking with just the config-file(s) from the git clone, but then you say going into a subfolder has it broken again?

Presumably you must have selected a subfolder already - because otherwise you couldn't have seen messages, or run a `s`ave operation?

So starting from the top, with no other configuration files loaded, just the ones from the git-checkout, and invoking like so:

     $  ./lumail2 --no-default --load-file ./lumail2.lua --load-path ./lib 2> error.log

What are the precise series of steps you're taking?  You start and you have a list of maildirs, you select one to open the index and view the list of messages?  Then you press `s` to save, enter a destination and finally see an error of some kind?

**Comment by RquasiR** [comment]
When I gitclone lumail2 I always do "make", "make test", "sudo make install".

My steps are:
1. $ rm -r .lumail2/cache/*  (after the last "^W")
2. $  cd lumail2/  (new folder after gitclone; I hope I cancelled the old one)
2. $ ./lumail2 --no-default --load-file ./lumail2.lua --load-path ./lib 2> error.log
3. I get the Maildir/subfolder list.
4. Pressing 55 to go to my personal folder
5. I go to the line with the mail I want to save elsewhere.
6. I press "s" and complete the path to the new folder, Enter.
7. No error!
8. I press "q" and go to the new folder, where I see the copied mail meanwhile thrice because I
    have always copied the same mail into the same new folder.

Now I'm going to use lumail2 as I always do and will try to save the mail again.

**Comment by RquasiR** [comment]
Now the normal procedure:

1. $ cd
2. $ lumail2 (I get the list of Maildir subfolders)
3. Pressing 55 to go quickly to my personal folder.
4. I choose the mail I wish to copy elsewhere (it's one with date 2016, wrong sorted in the 2017 mails)
5. Without invoking the mail I press "s" and complete the path to the new folder and enter.
6. ERROR: /etc/lumail2/lumail2.lua:1888: bad argument #1 to 'new' (string expected, got nil)

**Comment by skx** [comment]
Thank-you.  That was a perfect set of steps.

I think I can guess what is going on now.  You've described two different attempts:

* Launching the locally cloned git-version, via "` ./lumail2 --no-default --load-file  ...`"
   * This is bug-free
* Launching the system-wide installation you've previously made via `make install`.
   * This is broken.

The main difference between these two is whether `/etc/lumail2/lumail2.lua` is loaded or not.  In the first case it is ignored because of the `--no-default` flag, in the second it is used.

Looking into what `make install` does I see this:

    # if there is no config in-place, add the default
        if [ ! -e $(LUMAIL_HOME)/lumail2.lua ] ; then cp ./lumail2.lua $(LUMAIL_HOME)/lumail2.lua ; fi

So what I think is happening is clear: Your old, and system-wide, configuration file is still present because `make install` doesn't override it.

If I'm right you can fix things via this:

        sudo cp lumail2.lua /etc/lumail2/

For myself I think I can now switch to always overwriting that file, because all the documentation suggests that the global file shouldn't be touched - and instead a per-user file be created via the sample in `lumail2.user.lua`.

**Comment by RquasiR** [comment]
Congratulation!

After "sudo cp lumail2.lua /etc/lumail2/" and launching the system-wide installation the mail is copied without any error!!!
Thank you very much, Steve! Hard work, I guess!

Rudolf

**Comment by skx** [comment]
Todo:

* `make install` should overwrite the config-file.
   * This shouldn't cause people problems, but probably needs a warning.
