### ISSUE TITLE
Displaying a folder with lots of mails is CPU intensive

### ISSUE THREAD

**Issue by trou** [lumail/lumail2#63]
Hello,
I have a folder with 8k messages, when displaying all mails in it (on my slow Atom): 
* loading it takes ~ 20s
* just displaying the mails takes ~60% of CPU

**Comment by skx** [comment]
I expect opening a large folder to be slow, as we call index_view() to get the message-list.

`index_view()` will call `Message:format()` once for each message, even if it is not on the screen.  But that should only be slow the first time due to the caching.

Is it possible to see where it is hogging the CPU?

**Comment by trou** [comment]
I'll try to profile :)

**Comment by skx** [comment]
I suspect there are two issues here:

* When viewing a maildir *every* message is accessed to do the sorting.
* When viewing a maildir *every* message has `:format()` called on it, even if it isn't to be displayed.

We could optimize the latter by getting the current offset and only formatting them from `$current - height()`  to `$current + hieght()`, but the former will still cripple things as each message is opened for the date-header reading.

It might be that we can add caching to `CMessage::headers()` which is what will be used for:

* Sender:
* Subject:
* Date:

That would cut down the opening of a message to one time instead of three times for each display, but after that the easy options will harder to spot.

I'll add the caching there tomorrow, and if that helps great.  If not I'll try to reproduce on a large maildir of my own.  (Sadly I'm using SSDs and lots of RAM so I struggle to find a slow folder.)

**Comment by skx** [comment]
Does this patch help?

The intention is to persist the cached formatted messages.  If this is the cause of the slowdown it will help.  If it is the sorting, it won't.  But you can set `index.sort=none` to rule that out.

[cache.diff.txt](https://github.com/lumail/lumail2/files/33734/cache.diff.txt)

**Comment by skx** [comment]
Ugh.  Bad patch.

This is what I meant:
[cache.diff.txt](https://github.com/lumail/lumail2/files/33742/cache.diff.txt)

**Comment by trou** [comment]
cache.diff.txt doesn't change anything. The profiling gives : 
```
 30.66      0.33     0.33  3249357     0.00     0.00  l_CheckCMessage(lua_State*, int)
 16.98      0.51     0.18                             l_CMessage_path(lua_State*)
  7.55      0.59     0.08    16570     0.00     0.01  CMessage::headers()
```
but the cumulative time is low so I suspect most of the time is spent running Lua code.

**Comment by skx** [comment]
I think that two changes should have helped:

* The lua-based caching.
* The message-header caching - which is where `CMessage::headers()` comes from in your list.

Is it still bad?  To the extent we need to make more changes?

**Comment by trou** [comment]
Yes definitely. Scrolling in messages is painfully slow. Now CPU usage is oscillating between 20 and 50%.

**Comment by skx** [comment]
OK I'm sorry to hear that.  I thought the caching would have helped - but I can imagine there are improvements that can be made.

Tonight I'll make a new release, and this will be the priority once that is out of the way.
