### ISSUE TITLE
error in luarocks.d/date.lua

### ISSUE THREAD

**Issue by RquasiR** [lumail/lumail2#99]
Lumail2 d9db on debian/jessie:

"An error was caught /etc/lumail2/luarocks.d/date.lua:315: duplicate value:                                                                                     │
un, 1 Apr 2007 15:53:13 GMT-07:00

- Compilation is ok (after git clone https://github.com/lumail/lumail2/)
- I copied date.lua --> /etc/lumail2/luarocks.d/, too.

Error occurred invoking a big folder directly beneath ~/Maildir, but doesn't happen
with every folder!

**Comment by RquasiR** [comment]
To be more precise: Error occurs only with one folder: 
Error possibly data dependant?

**Comment by skx** [comment]
Lumail parses the `Date:` header of each mail, for display in the index in a sorted order.  The parsing of the `Date` header is done via the external luarocks library - and that library is throwing an error.

I think that the error is genuine, the date that you've included is wrong - it contains both a timezone _and_ an offset.  I can reproduce this error just using the luarocks library like so:

      $ ./lumail2  --load-file ./t.lua 
      ERROR ./luarocks.d/date.lua:315: duplicate value: 
      1 Apr 2007 15:53:13 GMT-07:00
      ........................^

      $cat t.lua
      package.path = package.path .. ';./luarocks.d/?.lua'
      local date   = require("date")
      local str = "1 Apr 2007 15:53:13 GMT-07:00"
      local d1      = date(str)
      local seconds = date.diff(d1, date.epoch()):spanseconds()
      print( "The date parsed to " .. seconds .. " seconds" )

So this is a bug, but we can probably work around it.  Or otherwise catch it.

**Comment by RquasiR** [comment]
Would a grep produced file help with solely the "Date:" headers like:

1163080642.1568_22.lvps87-230-4-153:2,S:Date: Thu, 9 Nov 2006 14:57:22 +0100
msg.yKCb:2,S:Date: Thu, 6 May 2010 08:31:36 +0200
msg.ZYhZ:2,S:Date: Sat, 28 Jun 2014 08:05:41 +0200
...

But reading a file with more than 3100 lines would be no fun ...

**Comment by skx** [comment]
The single example in your original bug-report was fine, it was enough to show that the date-parsing luarocks library I've included has a bug in it.  We'll either work around it, or fix it.

If further issues come up with other dates then we'll deal with them as and when.
